"""added subtable

Revision ID: 90fdf44978f0
Revises: 
Create Date: 2024-12-16 09:44:48.533628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fdf44978f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('imgname')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('img')
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('img', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('imgname', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
